# Generated by Django 3.1.1 on 2020-09-04 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_cricket_statistics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistic',
            old_name='batting_aggregate',
            new_name='batting_runs',
        ),
    ]
