# Generated by Django 3.1.1 on 2020-09-15 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_cricket_statistics', '0002_auto_20200905_0345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistic',
            old_name='number_of_matches',
            new_name='matches',
        ),
    ]
