# Generated by Django 3.1.1 on 2020-09-16 08:29

from django.db import migrations, models
import django.db.models.deletion


def forward_eleven_number_one_to_one(apps, schema_editor):
    """Assign first eleven number one-to-one field."""
    Player = apps.get_model("django_cricket_statistics", "Player")
    FirstElevenNumber = apps.get_model("django_cricket_statistics", "FirstElevenNumber")
    db_alias = schema_editor.connection.alias

    for player in Player.objects.using(db_alias).exclude(first_XI_number__isnull=True):
        player.first_eleven_number = FirstElevenNumber.objects.using(db_alias).get(
            pk=player.first_XI_number
        )


def reverse_eleven_number_one_to_one(apps, schema_editor):
    """Revert first eleven number one-to-one field."""
    Player = apps.get_model("django_cricket_statistics", "Player")
    db_alias = schema_editor.connection.alias

    for player in Player.objects.using(db_alias).exclude(
        first_eleven_number__isnull=True
    ):
        player.first_XI_number = player.first_eleven_number.pk


class Migration(migrations.Migration):

    dependencies = [("django_cricket_statistics", "0004_create_first_eleven_data")]

    operations = [
        migrations.AddField(
            model_name="player",
            name="first_eleven_number",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="django_cricket_statistics.firstelevennumber",
            ),
        ),
        migrations.RunPython(
            forward_eleven_number_one_to_one, reverse_eleven_number_one_to_one
        ),
        migrations.RemoveField(model_name="player", name="first_XI_number"),
    ]
